# Generated by Django 5.2.3 on 2025-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('type', models.CharField(max_length=50, verbose_name='商品类别')),
                ('img', models.ImageField(upload_to='banner_goods', verbose_name='商品图片')),
                ('description', models.CharField(max_length=250, verbose_name='版权信息')),
                ('order', models.IntegerField(verbose_name='顺序')),
            ],
            options={
                'verbose_name_plural': '商品轮播图',
            },
        ),
    ]
