# Generated by Django 5.2.3 on 2025-06-15 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_banner_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_Goods_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='商品类别')),
            ],
        ),
        migrations.AlterField(
            model_name='banner_goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart.banner_goods_type'),
        ),
    ]
