# Generated by Django 5.2.3 on 2025-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_banner_goods_type_alter_banner_goods_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='/welcome/welcome.jpg', upload_to='welcome', verbose_name='图片')),
                ('order', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner_goods_type',
            options={'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterField(
            model_name='banner_goods',
            name='description',
            field=models.CharField(max_length=250, verbose_name='商品详情'),
        ),
    ]
