# Generated by Django 5.2.3 on 2025-06-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0004_welcome_alter_banner_goods_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copyright',
            name='id',
        ),
        migrations.AlterField(
            model_name='copyright',
            name='order',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='顺序'),
        ),
    ]
