# Generated by Django 5.2.3 on 2025-06-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_remove_copyright_id_alter_copyright_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='copyright',
            name='order',
            field=models.IntegerField(auto_created=True, verbose_name='顺序'),
        ),
    ]
