# Generated by Django 5.2.3 on 2025-06-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_copyright_id_alter_copyright_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='info_img',
            field=models.ImageField(default='/default.png', upload_to='activity', verbose_name='活动图片'),
        ),
        migrations.AddField(
            model_name='joinrecord',
            name='participation',
            field=models.BooleanField(default=False, verbose_name='是否已参加'),
        ),
        migrations.AddField(
            model_name='joinrecord',
            name='point',
            field=models.IntegerField(default=0, verbose_name='活动积分'),
        ),
    ]
