# Generated by Django 5.2.3 on 2025-06-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0007_activity_info_img_joinrecord_participation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyright',
            name='img_detail',
            field=models.ImageField(default='/default.png', upload_to='copyright/copyright_detail', verbose_name='版权图片'),
        ),
    ]
