# Generated by Django 5.2.3 on 2025-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0008_copyright_img_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='openid',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='微信小程序id'),
        ),
    ]
