# Generated by Django 5.2.3 on 2025-07-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0009_userinfo_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(upload_to='avatar', verbose_name='头像'),
        ),
    ]
