# Generated by Django 5.2.3 on 2025-07-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0011_alter_userinfo_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatar/avatar.png', upload_to='avatar', verbose_name='头像'),
        ),
    ]
